services:
  ghost:
    image: ghost:latest
    container_name: ghost_cms
    restart: unless-stopped
    ports:
      - "2368:2368"
    volumes:
      - ./content:/var/lib/ghost/content
    environment:
      NODE_ENV: development
      url: http://localhost:2368
    command: >
      bash -c "
        GHOST_VERSION=$$(ls /var/lib/ghost/versions | sort -V | tail -n 1) &&
        rm -rf /var/lib/ghost/versions/$$GHOST_VERSION/content &&
        ln -s /var/lib/ghost/content /var/lib/ghost/versions/$$GHOST_VERSION/content &&
        docker-entrypoint.sh node current/index.js
      "