services:
  ghost:
    image: ghost:latest
    container_name: ghost_cms
    restart: unless-stopped
    ports:
      - "2368:2368"
    volumes:
      - ./content:/var/lib/ghost/content
    environment:
      NODE_ENV: development
      url: http://localhost:2368
